### PR TITLE
Remove packages

### LINKED ISSUE #22: Remove some pigen packages
Here's the list of packages to remove, from @fheslouin:

- ~~[`firmware-atheros`](https://packages.debian.org/bullseye/firmware-atheros) 31M: Binary firmware for Qualcomm Atheros wireless cards~~
- ~~[`firmware-libertas`](https://packages.debian.org/bullseye/firmware-libertas) 25M: Binary firmware for Marvell wireless cards~~
- ~~[`firmware-misc-nonfree`](https://packages.debian.org/bullseye/firmware-misc-nonfree) 35M: Binary firmware for various drivers in the Linux kernel~~
- ~~[`firmware-realtek`](https://packages.debian.org/bullseye/firmware-realtek) 3M: Binary firmware for Realtek wired/wifi/BT adapters~~
- [`pi-bluetooth`](https://github.com/RPi-Distro/pi-bluetooth) <1M: Loads BCM43430A1 firmware on boot 
- [`v4l-utils`](https://packages.debian.org/bullseye/v4l-utils) 2.5M: Collection of command line video4linux utilities
- [`python-rpi.gpio`](https://pypi.org/project/RPi.GPIO/) <1M:  a Python module to control the GPIO on a Raspberry Pi.
- [`python-gpiozero`](https://pypi.org/project/gpiozero/) <1M: A simple interface to GPIO devices with [Raspberry Pi](https://www.raspberrypi.org/),

Unfortunately, we can't remove the drivers as we need to support external WiFI dongles as Pi Zero, Pi and Pi 2 have no integrated WiFi chipset.

@fheslouin @letompouce, please confirm it's OK to include drivers in the base image and maybe remove it in your post-install step.

### PR DESCRIPTION
**Pull request by rgaudin**
Fixes #22 by adding capability to remove packages using our `packages` file. We advertised the feature but it wasn't there  🤷‍♂️

### CODE REVIEW

**Review by Bastien-BSF — APPROVED** [review]
LGTM

**Comment by kelson42** [comment]
@letompouce I guess your approval/feedback is expected here.

**Comment by rgaudin** [comment]
No we already got it but this merges after runtime config

**Comment by rgaudin** [comment]
Added fix for #19 which is both straight-forward and matches with this PR

**Pull request merged**
